### ISSUE TITLE
error  while converting 

### ISSUE THREAD

**Issue by sridhar9999** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#18]
Namespace(model='ckpt_woflow', test_dir='test_sample0', test_img='', use_gpu=1)
'grep' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "main_woflow.py", line 30, in <module>
    os.environ["CUDA_VISIBLE_DEVICES"]=str(np.argmax( [int(x.split()[2]) for x in subprocess.Popen("nvidia-smi -q -d Memory | grep -A4 GPU | grep Free", shell=True, stdout=subprocess.PIPE).stdout.readlines()]))
  File "<__array_function__ internals>", line 6, in argmax
  File "E:\mi\lib\site-packages\numpy\core\fromnumeric.py", line 1153, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "E:\mi\lib\site-packages\numpy\core\fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "E:\mi\lib\site-packages\numpy\core\fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

(base) E:\animegan\video attack\Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity-master>python main_woflow.py --model ckpt_woflow --use_gpu 1 --test_dir test_sample0

how to fix it

**Comment by sridhar9999** [comment]
File "main_woflow.py", line 30, in <module>
    os.environ["CUDA_VISIBLE_DEVICES"]=str(np.argmax( [int(x.split()[2]) for x in subprocess.Popen("nvidia-smi -q -d Memory | grep -A4 GPU | grep Free", shell=True, stdout=subprocess.PIPE).stdout.readlines()]))
  File "<__array_function__ internals>", line 6, in argmax
  File "E:\mi\lib\site-packages\numpy\core\fromnumeric.py", line 1153, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "E:\mi\lib\site-packages\numpy\core\fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "E:\mi\lib\site-packages\numpy\core\fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

**Comment by ChenyangLEI** [comment]
The code is tested on **Ubuntu** instead of **windows**. Maybe you need to use other methods to choose the GPU.
