### ISSUE TITLE
when i use main_whole to inference,some unexpected mistake occured

### ISSUE THREAD

**Issue by qianmingduowan** [ChenyangLEI/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity#6]
Traceback (most recent call last):
  File "main_whole.py", line 11, in <module>
    import flow_warp as flow_warp_op
  File "/home/qianming/code/Fully-Automatic-Video-Colorization/flow_warp.py", line 4, in <module>
    tf.resource_loader.get_path_to_datafile("./lib/flow_warp.so"))
  File "/home/qianming/anaconda3/envs/torch/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.8.0: cannot open shared object file: No such file or directory

**Comment by ChenyangLEI** [comment]
Are you using tensorflow 1.2.0?

**Comment by qianmingduowan** [comment]
> Are you using TensorFlow 1.2.0?

No, I use TensorFlow 1.14.0 before,  I will try 1.2.0. Before this, I have another question, Is your Cuda version is  8.0?

**Comment by ChenyangLEI** [comment]
I used cuda 8.0 before. Now I use Cuda 9.0/9.1 and it is still ok.
